# Generated by Django 6.1 on 2026-08-11 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_taken_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='ai_caption',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='hashtags',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='photos.album'),
        ),
    ]
