# Generated by Django 6.1 on 2026-08-12 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calculator',
            new_name='Calculation',
        ),
    ]
